name: Build windows open3d library

on:
  push:
    branches:
      - main

env:
  install_path: "C:/open3d_win"
  ver_tag: "v0.20.0"

jobs:
  Windows:
    runs-on: windows-2022

    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Download latest open3d 
        shell: bash
        run: |
          git clone --branch ${{ env.ver_tag }} --depth 1 https://github.com/isl-org/Open3D.git
          
      - name: Configure build for amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.29

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.6.0
        with:
          vulkan_version: 1.3.231.1
          install_runtime: false
          cache: true

      - name: Build
        run: |
          cd Open3D && md build && cd build
          cmake .. -DBUILD_SHARED_LIBS=OFF -DSTATIC_WINDOWS_RUNTIME=ON -A x64 -DCMAKE_INSTALL_PREFIX=${{env.install_path}}
          cmake --build . --config Release --target INSTALL --parallel 4
      
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: open3d_win
          path: ${{ env.install_path }}
                  
